### ISSUE TITLE
Incorrect initial resource generation

### ISSUE THREAD

**Issue by sqduong** [hherman1/CatanClient#48]
when a settlement is placed, the correct number of resources the player receives is incorrect. (values are correct, but maybe mapped to the wrong resource?) I think this only happens for wheat, wood, and brick.

**Comment by carstenhaas** [comment]
I'm not having any problems with this - can anybody verify?

**Comment by hherman1** [comment]
I can't tell if the resources are correct or not, they don't seem to match the tiles if they're supposed to though.

**Comment by carstenhaas** [comment]
You guys will have to show me in class tomorrow - I'm having zero errors with this

**Comment by hherman1** [comment]
![image](https://cloud.githubusercontent.com/assets/611822/14593712/789aacb0-04f3-11e6-8857-ead0452e7905.png)

**Comment by carstenhaas** [comment]
So this was working on both mine and stephanie's in class - can hunter and mack pull one more time and verify this is fixed?

**Comment by hherman1** [comment]
Seems fine now
