### ISSUE TITLE
UI Glitch

### ISSUE THREAD

**Issue by MackHartley** [hherman1/CatanClient#56]
![image](https://cloud.githubusercontent.com/assets/10659285/14658185/a17fce52-0657-11e6-9b98-4cc7ca1541bb.png)

**Comment by hherman1** [comment]
what shoudl this look like instead?

**Comment by MackHartley** [comment]
Since there are 10 roads, it spilled over onto the next line in Player 2's box

**Comment by hherman1** [comment]
this is fixed, right?
