### ISSUE TITLE
Can the player tabs be widened slightly? - the last number is a little covered in the new font

### ISSUE THREAD

**Issue by carstenhaas** [hherman1/CatanClient#84]

**Comment by MackHartley** [comment]
Could you perhaps take a picture of what the issue is? I am looking at the game right now and the spacing seems pretty "spacious"

**Comment by carstenhaas** [comment]
![capture](https://cloud.githubusercontent.com/assets/14096103/14829283/2744ecd6-0bb0-11e6-9a91-78f3cd6d9ca0.JPG)

those 0s on the edge
