### ISSUE TITLE
SubPhase is always set to 0 (which is the building phase)

### ISSUE THREAD

**Issue by MackHartley** [hherman1/CatanClient#85]
Could @hherman1 or @carstenhaas take a look at this? Also, would it be better to put the subphases together with the phases? I know that they are a little different, but I think it makes sense for them to be together as well.

**Comment by carstenhaas** [comment]
I'll resolve this tomorrow with hunter. It actually also switches to robbing subphase successfully, but the trading subphase is problematic. Subphases are kept discrete beccause the subphases only cycle within the normal phase - initialization has only building subphase

**Comment by carstenhaas** [comment]
Resolved
