### ISSUE TITLE
why does it have to be man? 

### ISSUE THREAD

**Issue by sqduong** [hherman1/CatanClient#93]
replace 'man' with 'settler'
![screen shot 2016-04-28 at 12 52 13 pm](https://cloud.githubusercontent.com/assets/10660593/14895797/147bf0a4-0d40-11e6-97b1-d368f431e2fe.png)

**Comment by hherman1** [comment]
this is purely temporary anyways

**Comment by hherman1** [comment]
Speaking of, what should it look like?

**Comment by sqduong** [comment]
there is a longest road card image, but maybe that is too big? Maybe there should there be another symbol for longest road to use here.

**Comment by hherman1** [comment]
Is this solved now?

**Comment by sqduong** [comment]
yes

_Stephanie Duong_

_Jack Kent Cooke College Scholar_
_Macalester College, Class of 2016_

_sduong@macalester.edu sduong@macalester.edu(909) 296-0557_

**Comment by sqduong** [comment]
resolved
